title: "Umi Syahirah"
author: "Umi Syahirah"
description: "Resources and thoughts"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: false        # display a grey frame on large screens
show_sidebar: true          # show a sidebar instead of the usual header
show_minimal: true            # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: "Home", icon: home}
  - {file: "README.md", title: "About me", icon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "umi.syahirah@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/umisyahirah"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
